package com.manus.assistant

import android.content.Context

class CloudStorageManager(context: Context) {

    private val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    fun uploadPlaceholder(fileName: String): String {
        val updated = loadFiles().toMutableSet().apply { add(fileName) }
        prefs.edit().putStringSet(KEY_FILES, updated).apply()
        return "Queued \"$fileName\" for placeholder cloud upload."
    }

    fun createDownloadPlaceholder(): DownloadPlaceholder =
        DownloadPlaceholder(
            fileName = "cloud_assistant_note.txt",
            contents = buildString {
                appendLine("Cloud download placeholder")
                appendLine("Generated by the Personal Assistant Android app.")
                appendLine("Replace this content with a real cloud-backed download flow.")
            }
        )

    fun listFilesMessage(): String {
        val files = loadFiles().sorted()
        return if (files.isEmpty()) {
            "Cloud storage placeholder is empty."
        } else {
            "Cloud storage placeholder files:\n" + files.joinToString("\n") { "• $it" }
        }
    }

    private fun loadFiles(): Set<String> =
        prefs.getStringSet(KEY_FILES, DEFAULT_FILES)?.toSet() ?: DEFAULT_FILES

    data class DownloadPlaceholder(
        val fileName: String,
        val contents: String
    )

    companion object {
        private const val PREFS_NAME = "cloud_storage_prefs"
        private const val KEY_FILES = "cloud_files"
        private val DEFAULT_FILES = setOf(
            "assistant-handbook.txt",
            "conversation-backup.json"
        )
    }
}
